name: Program Docker Image CI

on:
  push:
    branches:
      - "main" 
    paths:
      - "Corona.Pageant.Program/**"
      - "Corona.Pageant.Shared/**"
      - ".github/workflows/program-docker-publish.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true          

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: glenster75
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: glenster75/coronapageant25program
          tags: latest
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          file: ./Corona.Pageant.Program/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }},glenster75/coronapageant25program:v1.0.${{ github.run_number }}
          labels: ${{ steps.meta.outputs.labels }}

  # run_onprem:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Check out the repo
  #       uses: actions/checkout@v3
        
  #     - name: Publish latest containers
  #       run: |
  #         docker ps -aq | xargs docker stop | xargs docker rm
  #         docker-compose pull
  #         docker-compose up -d
