name: Web Viewer Docker Image CI

on:
  push:
    branches:
      - "main" 
    paths:
      - "Corona.Pageant.Viewer/**"
      - "Corona.Pageant.Shared/**"
      - ".github/workflows/viewer-docker-publish.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true          

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: glenster75
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: glenster75/coronapageant25viewer
          tags: latest
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          file: ./Corona.Pageant.Viewer/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # run_onprem:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Check out the repo
  #       uses: actions/checkout@v3

  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
  #       with:
  #         username: glenster75
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
        
  #     - name: Publish latest containers
  #       run: |
  #         docker ps -aq | xargs docker stop | xargs docker rm
  #         docker-compose pull
  #         docker-compose up -d
